#!/bin/bash


# Variaveis locais
ifaceEx="enp0s3"            # Interface de rede externa
ifaceIn="enp0s8"            # Interface de rede interna
localnet="10.10.10.0/24"  # endereço da rede local                  


#==  Funcoes para definicao de regras =============================================================#


local(){
    # Funcao para configuracao das regras de firewall para comunicacao local

    # Libera a comunicacao (I/O) do servidor com a rede local e com a internet
    # Permite trafego TCP e UDP de entrada e saida nas portas
    # 80, 443, 53, 123 (HTTP, HTTPS, DNS, NTP)
    iptables -t filter -A INPUT -i $ifaceEx -p tcp -m multiport --sports 80,443 -j ACCEPT
    iptables -t filter -A INPUT -i $ifaceEx -p udp -m multiport --sports 53,123 -j ACCEPT
    iptables -t filter -A OUTPUT -o $ifaceEx -p tcp -m multiport --dports 80,443 -j ACCEPT
    iptables -t filter -A OUTPUT -o $ifaceEx -p udp -m multiport --dports 53,123 -j ACCEPT

    # Libera todo o trafego da lo na rede
    iptables -t filter -A INPUT -i lo -j ACCEPT
    iptables -t filter -A OUTPUT -o lo -j ACCEPT

    # Libera o ping (ICMP) no localhost
    iptables -t filter -A INPUT -i $ifaceEx -p icmp --icmp-type 0 -j ACCEPT
    iptables -t filter -A INPUT -i $ifaceIn -p icmp --icmp-type 0 -j ACCEPT
    iptables -t filter -A OUTPUT -o $ifaceEx -p icmp --icmp-type 8 -j ACCEPT
    iptables -t filter -A OUTPUT -o $ifaceIn -p icmp --icmp-type 8 -j ACCEPT

    # Libera o trafego TCP do Squid (3128)
    iptables -t filter -A INPUT -i $ifaceIn -p tcp --dport 3128 -j ACCEPT
    iptables -t filter -A OUTPUT -o $ifaceIn -p tcp --sport 3128 -j ACCEPT

    # Libera trafego nas portas do Samba (139 e 445)
    iptables -t filter -A INPUT -p tcp -m multiport --dports 139,445 -j ACCEPT
    iptables -t filter -A OUTPUT -p tcp -m multiport --sports 139,445 -j ACCEPT
    
    # SSH
    iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT
    iptables -t filter -A OUTPUT -p tcp --sport 22 -j ACCEPT
}


forward(){
    # Funcao para encaminhamento de trafego entre WAN e LAN

    # Libera o trafego entre a INTERNET e a REDE LOCAL
    iptables -t filter -A FORWARD -i $ifaceEx -p tcp -m multiport --sports 80,443 -d $localnet -j ACCEPT
    iptables -t filter -A FORWARD -i $ifaceEx -p udp -m multiport --sports 53,123 -d $localnet -j ACCEPT
    iptables -t filter -A FORWARD -i $ifaceIn -p tcp -m multiport --dports 80,443 -s $localnet -j ACCEPT
    iptables -t filter -A FORWARD -i $ifaceIn -p udp -m multiport --dports 53,123 -s $localnet -j ACCEPT

    # Libera o ping entre a INTERNET e a REDE LOCAL
    iptables -t filter -A FORWARD -i $ifaceIn -p icmp --icmp-type 8 -s $localnet -j ACCEPT
    iptables -t filter -A FORWARD -o $ifaceIn -p icmp --icmp-type 0 -d $localnet -j ACCEPT
    iptables -t filter -A FORWARD -i $ifaceEx -p icmp --icmp-type 0 -d $localnet -j ACCEPT
    iptables -t filter -A FORWARD -o $ifaceEx -p icmp --icmp-type 8 -s $localnet -j ACCEPT
}


internet(){ 
    # Funcao para habilitar o compartilhamento da internet entre as redes

    # Habilita o encaminhamento de IP
    sysctl -w net.ipv4.ip_forward=1

    # Configura NAT para o trafego da LAN para a Internet
    iptables -t nat -A POSTROUTING -s $localnet -o $ifaceEx -j MASQUERADE
    
    # Direcionar navegacao na porta HTTP (80) para a porta do proxy/squid (3128)
    iptables -t nat -A PREROUTING -i $ifaceIn -p tcp --dport 80 -j REDIRECT --to-port 3128
}


default(){
    # Funcao para definir as regras padrao

    # Bloqueia tudo que não foi explicitamente liberado
    iptables -t filter -P INPUT DROP
    iptables -t filter -P OUTPUT DROP
    iptables -t filter -P FORWARD DROP
}


#==  Funcoes de controle  =========================================================================#


iniciar(){
    # Funcao para iniciar o firewall

    local
    forward
    default
    internet
}


parar(){
    # Funcao para parar o firewall

    iptables -t filter -P INPUT ACCEPT
    iptables -t filter -P OUTPUT ACCEPT
    iptables -t filter -P FORWARD ACCEPT
    iptables -t filter -F
}


#==  Script para controle do firewall  ============================================================#


case $1 in
start|Start|START)iniciar;;
stop|Stop|STOP)parar;;
restart|Restart|RESTART)parar;iniciar;;
listar|list)iptables -t filter -nvL;;
vi|conf)sudo vi /usr/local/sbin/firewall;;
*)echo "usage: 
firewall [start|stop|restart|list|vi]";;
esac
