#!/bin/bash

# Parameters
ifaceIn="enp0s8"
ifaceEx="enp0s3"
localnet="192.168.0.0/24"
externet=0
#===============================================================================================================#


local(){ 

    # Libera a comunicacao (I/O) do servidor com a rede local e com a internet:
    	iptables -t filter -A INPUT -i $ifaceEx -p tcp -m multiport --sports 80,443 -j ACCEPT
    	iptables -t filter -A INPUT -i $ifaceEx -p udp -m multiport --sports 53,123 -j ACCEPT
    	iptables -t filter -A OUTPUT -o $ifaceEx -p tcp -m multiport --dports 80,443 -j ACCEPT
    	iptables -t filter -A OUTPUT -o $ifaceEx -p udp -m multiport --dports 53,123 -j ACCEPT

    # Libera o trafego da lo na rede:
    	iptables -t filter -A INPUT -i lo -j ACCEPT
    	iptables -t filter -A OUTPUT -o lo -j ACCEPT

    # Libera o ping na rede local (protocolo icmp):
    	iptables -t filter -A INPUT -i $ifaceEx -p icmp --icmp-type 8 -s 0/0 -j ACCEPT
    	iptables -t filter -A OUTPUT -o $ifaceEx -p icmp --icmp-type 0 -d 0/0 -j ACCEPT

    # Libera a porta do Squid:
    	iptables -t filter -A INPUT -i $ifaceIn -p tcp --dport 3128 -j ACCEPT
    	iptables -t filter -A OUTPUT -o $ifaceIn -p tcp --sport 3128 -j ACCEPT

    # Libera a porta do SSH:
    	iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT
    	iptables -t filter -A OUTPUT -p tcp --sport 22 -j ACCEPT

    # Libera as portas do Samba:
    	iptables -t filter -A INPUT -p tcp -m multiport --dports 139,445 -j ACCEPT
    	iptables -t filter -A OUTPUT -p tcp -m multiport --sports 139,445 -j ACCEPT

    # Libera as portas do SPEEDTEST OOKLA:
		iptables -t filter -A INPUT -p tcp --dport 5060 -m state --state NEW,ESTABLISHED -j ACCEPT        
		iptables -t filter -A INPUT -p tcp --sport 5060 -m state --state NEW,ESTABLISHED -j ACCEPT        
		iptables -t filter -A INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT        
		iptables -t filter -A INPUT -p tcp --sport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT 
}


forward(){

    # Libera o trafego entre WAN e LAN:
    	iptables -t filter -A FORWARD -i $ifaceEx -p tcp -m multiport --sports 80,443 -d $localnet -j ACCEPT
    	iptables -t filter -A FORWARD -i $ifaceEx -p udp -m multiport --sports 53,123 -d $localnet -j ACCEPT
    	iptables -t filter -A FORWARD -i $ifaceIn -p tcp -m multiport --dports 80,443 -s $localnet -j ACCEPT
    	iptables -t filter -A FORWARD -i $ifaceIn -p udp -m multiport --dports 53,123 -s $localnet -j ACCEPT

    # Libera as portas do SPEEDTEST OOKLA:
		iptables -A FORWARD -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
		iptables -A FORWARD -p tcp --dport 5060 -m state --state NEW,ESTABLISHED -j ACCEPT
		iptables -A FORWARD -p tcp --sport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
		iptables -A FORWARD -p tcp --sport 5060 -m state --state NEW,ESTABLISHED -j ACCEPT

    # Libera o ping entre a WAN e LAN:
    	iptables -t filter -A FORWARD -i $ifaceIn -p icmp --icmp-type 8 -s $localnet -d 0/0 -j ACCEPT
    	iptables -t filter -A FORWARD -o $ifaceIn -p icmp --icmp-type 0 -d $localnet -s 0/0 -j ACCEPT
}


internet(){

    # Habilita o compartilhamento da internet entre as redes:
    	sysctl -w net.ipv4.ip_forward=1
    	iptables -t nat -A POSTROUTING -s $localnet -o $ifaceEx -j MASQUERADE

    # Direcionar navegacao para a porta do proxy/squid (3128):
    	iptables -t nat -A PREROUTING -i $ifaceIn -p tcp --dport 80 -j REDIRECT --to-port 3128
}


default(){

    # Determinar as regras padroes para o firewall:
    	iptables -t filter -P INPUT DROP
    	iptables -t filter -P OUTPUT DROP
    	iptables -t filter -P FORWARD DROP
}


iniciar(){

    # Executa todas as funcoes criadas:
    	local
    	forward
    	default
    	internet
}


#===============================================================================================================#


parar(){

    # Desabilita o firewall:
    	iptables -t filter -P INPUT ACCEPT
    	iptables -t filter -P OUTPUT ACCEPT
    	iptables -t filter -P FORWARD ACCEPT
    	iptables -t filter -F
}


#===============================================================================================================#


# Script de execucao:
case $1 in
start|Start|START)iniciar;;
stop|Stop|STOP)parar;;
restart|Restart|RESTART)parar;iniciar;;
listar|list)iptables -t filter -nvL;;
vi|conf)sudo vi /usr/local/sbin/firewall;;
*)echo "\033[0;33mExecute o comando firewall com os parametros start, stop, restart, list, vi.";;
esac
